@startuml
actor User as User
participant Parser as ":Parser"
participant ChangeCommand as ":ChangeCommand"
participant Printer as ":Printer"

User -> Parser: input command "change NEW_BET_AMOUNT"
activate Parser

Parser -> ChangeCommand: new ChangeCommand(words, userData)
activate ChangeCommand

ChangeCommand -> ChangeCommand: userData.betAmount = NEW_BET_AMOUNT

ChangeCommand -> Printer: printBetAmount(NEW_BET_AMOUNT)
deactivate ChangeCommand

Parser -->> User: command executed
deactivate Parser
@enduml