@startuml
actor User as User
participant ChangeCommand as ":ChangeCommand"
participant Printer as ":Printer"

User -> ChangeCommand: execute()
activate ChangeCommand


ChangeCommand -> ChangeCommand: change()
activate ChangeCommand
ChangeCommand -> ChangeCommand: checkNumberOfWords(words)
activate ChangeCommand
ChangeCommand --> ChangeCommand
deactivate ChangeCommand
ChangeCommand -> ChangeCommand: checkNumerical(words[1])
activate ChangeCommand
ChangeCommand --> ChangeCommand
deactivate ChangeCommand
ChangeCommand -> ChangeCommand: checkCanBeInteger(words[1])
activate ChangeCommand
ChangeCommand --> ChangeCommand
deactivate ChangeCommand
ChangeCommand -> ChangeCommand: checkNonNegative(betAmount)
activate ChangeCommand
ChangeCommand --> ChangeCommand
deactivate ChangeCommand
ChangeCommand -> ChangeCommand: checkWithinBalance(betAmount, userData.balance)
activate ChangeCommand
ChangeCommand --> ChangeCommand
deactivate ChangeCommand

ChangeCommand -> Printer: printBetAmount()
activate Printer
Printer --> ChangeCommand
deactivate Printer
ChangeCommand --> ChangeCommand
deactivate ChangeCommand
ChangeCommand --> User
deactivate ChangeCommand
@enduml