@startuml
actor User as User
hide footbox
participant CheckCommand as ":CheckCommand"
participant Printer as ":Printer"
participant CoinflipException as ":CoinflipException"

User -> CheckCommand: execute()
activate CheckCommand


CheckCommand -> CheckCommand: check()
activate CheckCommand
CheckCommand -> CheckCommand: checkNumberOfWords(words)
activate CheckCommand
opt words.length != 2
create CoinflipException
CheckCommand -> CoinflipException : CoinflipException(CoinflipException.CHECK_INVALID_FORMAT)
activate CoinflipException
CoinflipException --> User
deactivate CoinflipException
end
CheckCommand --> CheckCommand
deactivate CheckCommand
CheckCommand -> CheckCommand: check(words[1])
activate CheckCommand
alt words[1] == "balance"
    CheckCommand -> CheckCommand: checkBalance()
    activate CheckCommand
    CheckCommand -> Printer: printBalance()
    activate Printer
    Printer --> CheckCommand
    deactivate Printer
    CheckCommand --> CheckCommand
    deactivate CheckCommand
else words[1] == "bet"
    CheckCommand -> CheckCommand: checkBet()
    activate CheckCommand
    CheckCommand -> Printer: printBetAmount()
    activate Printer
    Printer --> CheckCommand
    deactivate Printer
    CheckCommand --> CheckCommand
    deactivate CheckCommand
else words[1] == "history"
    CheckCommand -> CheckCommand: checkHistory()
    activate CheckCommand
    CheckCommand -> Printer: printStats()
    activate Printer
    Printer --> CheckCommand
    deactivate Printer
    CheckCommand --> CheckCommand
    deactivate CheckCommand
end
note right of CheckCommand
The default of the above
switch case also throws an
exception but has been
omitted to prevent cluttering
end note
CheckCommand --> CheckCommand
deactivate CheckCommand

CheckCommand --> CheckCommand
deactivate CheckCommand
CheckCommand --> User
deactivate CheckCommand
@enduml
