@startuml
actor User as User
participant Parser as ":Parser"
participant CheckCommand as ":CheckCommand"
participant Printer as ":Printer"

User -> Parser: input command "check {COMMAND}"
activate Parser

Parser -> CheckCommand: new CheckCommand(COMMAND)
activate CheckCommand

alt COMMAND == "balance"
CheckCommand -> Printer: printBalance(...)
else COMMAND == "bet"
CheckCommand -> Printer: printBetAmount(...)
else COMMAND == "history"
CheckCommand -> Printer: printStats(...)
end

CheckCommand -->> Parser: command
deactivate CheckCommand

Parser -->> User: command
deactivate Parser
@enduml