@startuml
actor User as User
participant ExitCommand as ":ExitCommand"
participant Printer as ":Printer"

User -> ExitCommand: execute()
activate ExitCommand


ExitCommand -> ExitCommand: checkNumberOfWords(words)
activate ExitCommand
ExitCommand --> ExitCommand
deactivate ExitCommand

ExitCommand -> Printer: printBye()
activate Printer
Printer --> ExitCommand
deactivate Printer
ExitCommand --> User
deactivate ExitCommand
@enduml