@startuml
actor User as User
participant Parser as ":Parser"
participant ExitCommand as ":ExitCommand"
participant Printer as ":Printer"

User -> Parser: input command "exit"
activate Parser

Parser -> ExitCommand: new ExitCommand()
activate ExitCommand

ExitCommand -> Printer: printExitMessage()
deactivate ExitCommand

Parser -->> User: command executed
deactivate Parser
@enduml