@startuml
actor User as User
participant HelpCommand as ":HelpCommand"
participant Printer as ":Printer"

User -> HelpCommand: execute()
activate HelpCommand


HelpCommand -> HelpCommand: checkNumberOfWords(words)
activate HelpCommand
HelpCommand --> HelpCommand
deactivate HelpCommand

HelpCommand -> Printer: printHelp()
activate Printer
Printer --> HelpCommand
deactivate Printer
HelpCommand --> User
deactivate HelpCommand
@enduml