@startuml
actor User as User
hide footbox
participant HelpCommand as ":HelpCommand"
participant Printer as ":Printer"
participant CoinflipException as ":CoinflipException"

User -> HelpCommand: execute()
activate HelpCommand


HelpCommand -> HelpCommand: checkNumberOfWords(words)
activate HelpCommand
opt words.length != 1
create CoinflipException
HelpCommand -> CoinflipException : CoinflipException(CoinflipException.HELP_INVALID_FORMAT)
activate CoinflipException
CoinflipException --> User
deactivate CoinflipException
end
HelpCommand --> HelpCommand
deactivate HelpCommand

HelpCommand -> Printer: printHelp()
activate Printer
Printer --> HelpCommand
deactivate Printer
HelpCommand --> User
deactivate HelpCommand
@enduml
